doc getting started: change links to github
adfinis-sygroup/ansible-guide pull request #12
Opened 2017-10-31 12:35 UTC by keachi

2017-10-31 16:46 UTC, karras commented
LGTM

2017-11-01 09:36 UTC, karras requested changes

2017-11-01 09:36 UTC, karras commented on doc/getting_started.rst
> +This speeds up ansible operations considerably especially with many hosts.
s/ansible/Ansible

2017-11-01 09:38 UTC, karras commented on doc/getting_started.rst
> +This speeds up ansible operations considerably especially with many hosts.
Can you please replace all occurrences within the file? :)

2017-11-01 10:26 UTC, keachi commented
Please also add your review

2017-11-01 10:28 UTC, lordfolken approved these changes

2017-11-01 10:30 UTC, lordfolken approved these changes

2017-11-02 07:26 UTC, karras approved these changes

2017-11-02 07:26 UTC, merged