LICENSE CC-BY-SA added
adfinis-sygroup/ansible-guide pull request #3
Opened 2017-10-31 09:16 UTC by keachi

2017-10-31 12:20 UTC, karras requested changes

2017-10-31 12:20 UTC, karras commented on README.rst
> +This repository provides an example project with the ansible roles written by
s/ansible/Ansible/
s/with/for/

2017-10-31 12:20 UTC, karras commented on README.rst
> +Adfinis SyGroup AG. In addition, it contains a guide to ansible, written
s/ansible/Ansible/

2017-10-31 12:20 UTC, karras commented on README.rst
> +with Sphinx-doc_.
Fix this link please.

2017-10-31 12:29 UTC, keachi commented on README.rst
> +This repository provides an example project with the ansible roles written by
done

2017-11-01 09:26 UTC, karras approved these changes

2017-11-01 10:12 UTC, merged